In [28]:
import torch

a = torch.ones(3)
a

tensor([1., 1., 1.])

In [29]:
a[1]

tensor(1.)

In [30]:
a[2] = 10.0
a

tensor([ 1.,  1., 10.])

In [31]:
points = torch.zeros(6)
points[0] = 4
points[1] = 1.0
points[2] = 2.0
points[3] = 3.0
points[4] = 4.0
points[5] = 5.0

points

tensor([4., 1., 2., 3., 4., 5.])

In [32]:
float(points[0])

p = torch.tensor([[1.0,5.0],[2.0,7],[3,2]])
p

p.shape



p1 = torch.zeros(3,2)
p1

p2 =torch.tensor([[1,4],[4,5],[6,3]])
p2

p2[0,1]


p2[0]

tensor([1, 4])

In [33]:
# 索引张量
print(p2[1:])  ## 输出第一行之后的所有行
print(p2[1:,:]) # 输出第一行之后的所有行所有列
print(p2[1:,0])  ## 输出第一行之后的所有行 第一列
print(p2[None])  ## 增加大小为1的维度

tensor([[4, 5],
        [6, 3]])
tensor([[4, 5],
        [6, 3]])
tensor([4, 6])
tensor([[[1, 4],
         [4, 5],
         [6, 3]]])


In [34]:
img_t = torch.randn(3,5,5) ## shape channels rows columns
weights = torch.tensor([0.21212,0.34231,0.01919])

batch_t = torch.randn(2,3,5,5)



In [35]:
double_points = torch.ones(10,2,dtype = torch.double)
short_points = torch.tensor([[1,2],[3,4]],dtype=torch.float)


short_points.dtype
print(double_points)


tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]], dtype=torch.float64)


In [36]:
double_points = torch.zeros(10,2).double()
short_points = torch.ones(11,2).int()


double_points = torch.ones(10,2).to(torch.double)  
double_points

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]], dtype=torch.float64)

In [37]:
a = torch.ones(3,2)
a_t = torch.transpose(a,0,1)
a_t

b = torch.rand(5,dtype=torch.double)  ## 生成随机数
b




tensor([0.3705, 0.0240, 0.4585, 0.8253, 0.8338], dtype=torch.float64)

In [38]:
s = points.storage()  ## 查看张量存储 本质上还是一维数组
s[0] = 100
points

tensor([100.,   1.,   2.,   3.,   4.,   5.])

In [39]:
points = torch.tensor([[4,3],[31,1],[111,1221]])
second = points[1]
second.storage_offset()


second.size()



torch.Size([2])

In [40]:
second.shape

points.stride()

(2, 1)

In [41]:
points

## 取出子张量
second_point = points[1]  ## 得到的结果仍然是一个张量
second_point[0] = 10  ## 更改子张量的第一个元素
points


## 克隆一个张量
s_point = points[1].clone()
s_point[0] = 10111
points


## 张量的转置
points_t = points.t()
points_t

print(id(points_t.storage()) == id(points.storage()))

## 转换张量的形状
some_t = torch.ones(3,4,5)
transpose_t = some_t.transpose(0,2)  ## 转换两个维度

some_t.shape  ## 打印形状

transpose_t.shape

print(some_t.stride()) ## 计算步长

print(transpose_t.stride())  ## 计算步长

False
(20, 5, 1)
(1, 5, 20)


In [42]:
## 连续张量
print(points.is_contiguous())  ## 连续张量
print(points_t.is_contiguous())  ## 转置张量不是连续张量



True
False


In [43]:
points = torch.tensor([[4,1],[2,3],[6,7]])

## 将矩阵进行转置
points_t = points.t()

points_t  ## 转置的张量是不连续的

## 查看转置的张量的内存
points_t.storage()

# 查看转置张量的步长
points_t.stride()


## 将转置张量转换为连续张量
pp = points_t.contiguous()
pp

tensor([[4, 2, 6],
        [1, 3, 7]])

In [44]:
pp.storage()  ## 打印内存 是连续的张量


 4
 2
 6
 1
 3
 7
[torch.storage._TypedStorage(dtype=torch.int64, device=cpu) of size 6]

In [45]:
pp.stride()

(3, 1)

In [46]:
## 在GPU上创建一个张量
points_gpu = torch.tensor([[1.0,4.0],[2.0,1.0],[3.0,4.0]],device='cuda')

In [47]:
points_gpu = points.to(device = 'cuda')

## 将张量转回cpu
points_cpu = points_gpu.cpu()
points_cpu

tensor([[4, 1],
        [2, 3],
        [6, 7]])

In [48]:
points = torch.ones(3,4)
points_np  = points.numpy()  ## 张量转换为numpy数组
points_np

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [50]:
# 将numpy数组转换为张量
points = torch.from_numpy(points_np)
points

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
## 序列化张量
## 使用文件描述符代替文件名


## 保存张量
with open('./dlwpt-code/data/p1ch3/ourpoints.t','wb') as f:
    torch.save(points,f)

## 加载张量
with open('./dlwpt-code/data/p1ch3/ourpoints.t','rb') as f:
    points = torch.load(f)